export let records = [
  {"events":["steak","exercise","swim"],"werewolf":false},
  {"events":["bread","chocolate","danced","swim","smoked cigarette"],"werewolf":false},
  {"events":["steak","nachos","danced","cycling","swim"],"werewolf":false},
  {"events":["apple","ice cream","danced","computer","swim"],"werewolf":false},
  {"events":["potatoes","candy","danced","exercise","swim","market"],"werewolf":false},
  {"events":["apple","chocolate","danced","running","swim"],"werewolf":false},
  {"events":["pizza","danced","computer","work","smoked cigarette"],"werewolf":false},
  {"events":["bread","beer","danced","cycling","work"],"werewolf":false},
  {"events":["football","danced","work"],"werewolf":false},
  {"events":["pizza","danced","cycling","work"],"werewolf":false},
  {"events":["lasagna","nachos","danced","work"],"werewolf":false},
  {"events":["danced","swim","smoked cigarette"],"werewolf":false},
  {"events":["lettuce","danced","television","swim"],"werewolf":false},
  {"events":["spaghetti","danced","work"],"werewolf":false},
  {"events":["danced","computer","work"],"werewolf":false},
  {"events":["lettuce","nachos","danced","work"],"werewolf":false},
  {"events":["steak","danced","running","work"],"werewolf":false},
  {"events":["danced","work"],"werewolf":false},
  {"events":["football","reading","swim"],"werewolf":false},
  {"events":["bread","danced","swim"],"werewolf":false},
  {"events":["lasagna","danced","exercise","work"],"werewolf":false},
  {"events":["spaghetti","danced","reading","work"],"werewolf":false},
  {"events":["steak","ice cream","danced","television","work"],"werewolf":false},
  {"events":["spaghetti","nachos","work"],"werewolf":false},
  {"events":["football","ice cream","danced","cycling","work"],"werewolf":false},
  {"events":["spaghetti","fish","computer","swim"],"werewolf":true},
  {"events":["potatoes","ice cream","danced","computer","swim"],"werewolf":false},
  {"events":["potatoes","ice cream","danced","work"],"werewolf":false},
  {"events":["fish","danced","running","work"],"werewolf":false},
  {"events":["potatoes","exercise","work"],"werewolf":false},
  {"events":["pizza","ice cream","computer","work"],"werewolf":false},
  {"events":["lasagna","ice cream","work"],"werewolf":false},
  {"events":["football","candy","reading","swim"],"werewolf":false},
  {"events":["lasagna","nachos","danced","running","swim"],"werewolf":false},
  {"events":["potatoes","danced","work"],"werewolf":false},
  {"events":["steak","work"],"werewolf":false},
  {"events":["pizza","beer","work","market"],"werewolf":false},
  {"events":["lasagna","chocolate","cycling","work"],"werewolf":false},
  {"events":["spaghetti","danced","reading","work"],"werewolf":false},
  {"events":["spaghetti","chocolate","television","swim"],"werewolf":false},
  {"events":["bread","danced","exercise","swim"],"werewolf":false},
  {"events":["lasagna","fish","work"],"werewolf":true},
  {"events":["pizza","work"],"werewolf":false},
  {"events":["potatoes","exercise","work"],"werewolf":false},
  {"events":["danced","exercise","work"],"werewolf":false},
  {"events":["spaghetti","danced","television","work"],"werewolf":false},
  {"events":["pizza","cycling","swim"],"werewolf":false},
  {"events":["steak","danced","swim"],"werewolf":false},
  {"events":["steak","beer","danced","work"],"werewolf":false},
  {"events":["pizza","fish","candy","work"],"werewolf":true},
  {"events":["steak","fish","danced","reading","work"],"werewolf":false},
  {"events":["potatoes","fish","danced","work"],"werewolf":false},
  {"events":["steak","nachos","danced","exercise","work"],"werewolf":false},
  {"events":["pizza","fish","danced","television","swim"],"werewolf":false},
  {"events":["lasagna","danced","cycling","swim"],"werewolf":false},
  {"events":["football","fish","danced","computer","work","smoked cigarette"],"werewolf":false},
  {"events":["lettuce","danced","television","work"],"werewolf":false},
  {"events":["potatoes","danced","computer","work"],"werewolf":false},
  {"events":["bread","candy","work"],"werewolf":false},
  {"events":["potatoes","nachos","work"],"werewolf":false},
  {"events":["steak","chocolate","danced","swim"],"werewolf":false},
  {"events":["steak","danced","exercise","swim","smoked cigarette"],"werewolf":false},
  {"events":["apple","running","work"],"werewolf":false},
  {"events":["danced","work"],"werewolf":false},
  {"events":["lettuce","danced","running","work"],"werewolf":false},
  {"events":["candy","danced","work"],"werewolf":false},
  {"events":["apple","danced","computer","work"],"werewolf":false},
  {"events":["bread","danced","swim"],"werewolf":false},
  {"events":["football","danced","swim"],"werewolf":false},
  {"events":["spaghetti","candy","television","work","smoked cigarette"],"werewolf":false},
  {"events":["steak","chocolate","danced","work"],"werewolf":false},
  {"events":["lettuce","danced","work"],"werewolf":false},
  {"events":["steak","ice cream","danced","cycling","work"],"werewolf":false},
  {"events":["pizza","danced","work"],"werewolf":false},
  {"events":["spaghetti","fish","exercise","swim"],"werewolf":true},
  {"events":["bread","beer","computer","swim","smoked cigarette"],"werewolf":false},
  {"events":["danced","running","work"],"werewolf":false},
  {"events":["lettuce","fish","danced","work","smoked cigarette"],"werewolf":false},
  {"events":["lasagna","danced","television","work"],"werewolf":false},
  {"events":["football","danced","running","work"],"werewolf":false},
  {"events":["steak","danced","running","work"],"werewolf":false},
  {"events":["steak","reading","swim"],"werewolf":false},
  {"events":["potatoes","danced","running","work"],"werewolf":false},
  {"events":["lasagna","ice cream","work","smoked cigarette"],"werewolf":false},
  {"events":["football","fish","danced","swim"],"werewolf":false}
];
