export let records = [
  {"events":["steak","exercise","swim"],"werewolf":false},
  {"events":["bread","chocolate","brushed teeth","swim","touched tree"],"werewolf":false},
  {"events":["steak","nachos","brushed teeth","cycling","swim"],"werewolf":false},
  {"events":["apple","ice cream","brushed teeth","computer","swim"],"werewolf":false},
  {"events":["potatoes","candy","brushed teeth","exercise","swim","market"],"werewolf":false},
  {"events":["apple","chocolate","brushed teeth","running","swim"],"werewolf":false},
  {"events":["pizza","brushed teeth","computer","work","touched tree"],"werewolf":false},
  {"events":["bread","beer","brushed teeth","cycling","work"],"werewolf":false},
  {"events":["cauliflower","brushed teeth","work"],"werewolf":false},
  {"events":["pizza","brushed teeth","cycling","work"],"werewolf":false},
  {"events":["lasagna","nachos","brushed teeth","work"],"werewolf":false},
  {"events":["brushed teeth","swim","touched tree"],"werewolf":false},
  {"events":["lettuce","brushed teeth","television","swim"],"werewolf":false},
  {"events":["spaghetti","brushed teeth","work"],"werewolf":false},
  {"events":["brushed teeth","computer","work"],"werewolf":false},
  {"events":["lettuce","nachos","brushed teeth","work"],"werewolf":false},
  {"events":["steak","brushed teeth","running","work"],"werewolf":false},
  {"events":["brushed teeth","work"],"werewolf":false},
  {"events":["cauliflower","reading","swim"],"werewolf":false},
  {"events":["bread","brushed teeth","swim"],"werewolf":false},
  {"events":["lasagna","brushed teeth","exercise","work"],"werewolf":false},
  {"events":["spaghetti","brushed teeth","reading","work"],"werewolf":false},
  {"events":["steak","ice cream","brushed teeth","television","work"],"werewolf":false},
  {"events":["spaghetti","nachos","work"],"werewolf":false},
  {"events":["cauliflower","ice cream","brushed teeth","cycling","work"],"werewolf":false},
  {"events":["spaghetti","fish","computer","swim"],"werewolf":true},
  {"events":["potatoes","ice cream","brushed teeth","computer","swim"],"werewolf":false},
  {"events":["potatoes","ice cream","brushed teeth","work"],"werewolf":false},
  {"events":["fish","brushed teeth","running","work"],"werewolf":false},
  {"events":["potatoes","exercise","work"],"werewolf":false},
  {"events":["pizza","ice cream","computer","work"],"werewolf":false},
  {"events":["lasagna","ice cream","work"],"werewolf":false},
  {"events":["cauliflower","candy","reading","swim"],"werewolf":false},
  {"events":["lasagna","nachos","brushed teeth","running","swim"],"werewolf":false},
  {"events":["potatoes","brushed teeth","work"],"werewolf":false},
  {"events":["steak","work"],"werewolf":false},
  {"events":["pizza","beer","work","market"],"werewolf":false},
  {"events":["lasagna","chocolate","cycling","work"],"werewolf":false},
  {"events":["spaghetti","brushed teeth","reading","work"],"werewolf":false},
  {"events":["spaghetti","chocolate","television","swim"],"werewolf":false},
  {"events":["bread","brushed teeth","exercise","swim"],"werewolf":false},
  {"events":["lasagna","fish","work"],"werewolf":true},
  {"events":["pizza","work"],"werewolf":false},
  {"events":["potatoes","exercise","work"],"werewolf":false},
  {"events":["brushed teeth","exercise","work"],"werewolf":false},
  {"events":["spaghetti","brushed teeth","television","work"],"werewolf":false},
  {"events":["pizza","cycling","swim"],"werewolf":false},
  {"events":["steak","brushed teeth","swim"],"werewolf":false},
  {"events":["steak","beer","brushed teeth","work"],"werewolf":false},
  {"events":["pizza","fish","candy","work"],"werewolf":true},
  {"events":["steak","fish","brushed teeth","reading","work"],"werewolf":false},
  {"events":["potatoes","fish","brushed teeth","work"],"werewolf":false},
  {"events":["steak","nachos","brushed teeth","exercise","work"],"werewolf":false},
  {"events":["pizza","fish","brushed teeth","television","swim"],"werewolf":false},
  {"events":["lasagna","brushed teeth","cycling","swim"],"werewolf":false},
  {"events":["cauliflower","fish","brushed teeth","computer","work","touched tree"],"werewolf":false},
  {"events":["lettuce","brushed teeth","television","work"],"werewolf":false},
  {"events":["potatoes","brushed teeth","computer","work"],"werewolf":false},
  {"events":["bread","candy","work"],"werewolf":false},
  {"events":["potatoes","nachos","work"],"werewolf":false},
  {"events":["steak","chocolate","brushed teeth","swim"],"werewolf":false},
  {"events":["steak","brushed teeth","exercise","swim","touched tree"],"werewolf":false},
  {"events":["apple","running","work"],"werewolf":false},
  {"events":["brushed teeth","work"],"werewolf":false},
  {"events":["lettuce","brushed teeth","running","work"],"werewolf":false},
  {"events":["candy","brushed teeth","work"],"werewolf":false},
  {"events":["apple","brushed teeth","computer","work"],"werewolf":false},
  {"events":["bread","brushed teeth","swim"],"werewolf":false},
  {"events":["cauliflower","brushed teeth","swim"],"werewolf":false},
  {"events":["spaghetti","candy","television","work","touched tree"],"werewolf":false},
  {"events":["steak","chocolate","brushed teeth","work"],"werewolf":false},
  {"events":["lettuce","brushed teeth","work"],"werewolf":false},
  {"events":["steak","ice cream","brushed teeth","cycling","work"],"werewolf":false},
  {"events":["pizza","brushed teeth","work"],"werewolf":false},
  {"events":["spaghetti","fish","exercise","swim"],"werewolf":true},
  {"events":["bread","beer","computer","swim","touched tree"],"werewolf":false},
  {"events":["brushed teeth","running","work"],"werewolf":false},
  {"events":["lettuce","fish","brushed teeth","work","touched tree"],"werewolf":false},
  {"events":["lasagna","brushed teeth","television","work"],"werewolf":false},
  {"events":["cauliflower","brushed teeth","running","work"],"werewolf":false},
  {"events":["steak","brushed teeth","running","work"],"werewolf":false},
  {"events":["steak","reading","swim"],"werewolf":false},
  {"events":["steak","fish","reading","swim"],"werewolf":true},
  {"events":["potatoes","brushed teeth","running","work"],"werewolf":false},
  {"events":["lasagna","ice cream","work","touched tree"],"werewolf":false},
  {"events":["cauliflower","fish","brushed teeth","cycling","work"],"werewolf":false},
  {"events":["pizza","brushed teeth","running","work"],"werewolf":false},
  {"events":["lettuce","brushed teeth","work"],"werewolf":false},
  {"events":["bread","brushed teeth","television","swim"],"werewolf":false},
  {"events":["cauliflower","fish","brushed teeth","swim"],"werewolf":false}
];
